import { Box, Flex, Grid, GridItem } from "@chakra-ui/react";
import Head from "next/head";
import Filters from "../Components/Filters";
import Midsection from "../Components/Midsection";
import Productcard from "../Components/Productcard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   {/*   <Flex bg="#292929" pos="relative" w="1366px" h="768px">
        <Filters />
        <Midsection />
      </Flex>*/ }
      Hello
    </div>
  );
}
